development:
  adapter: mysql
  encoding: utf8
  database: MiniCRM_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: MiniCRM_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: MiniCRM_production
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
